version: '2'

services:

  app:
    container_name: geoip.app
    build: docker/php
    volumes:
      - .:/var/www

  nginx:
    container_name: geoip.nginx
    build: docker/nginx
    volumes_from:
      - app
    ports:
      - 8000:80
